---
- name: Listen httpd
  hosts: all
  sources:
  - ansible.eda.webhook:
      host: 0.0.0.0
      port: 5000
      
  rules:
  - name: Start My Job Template
    condition: event.payload.message == "Run My Job"
    action:
      run_job_template:
        name: "Test Job Template"
