---
- name: Listen httpd
  hosts: all
  sources:
  - ansible.eda.webhook:
      host: 0.0.0.0
      port: 8000
      
  rules:
  - name: Start My Job Template
    condition: "'restart' in event.payload.message"
    action:
      debug:
        var: event
